### ISSUE TITLE
Error accepting channel proposal when running demo twice without restarting ganache-cli

### ISSUE THREAD

**Issue by matthiasgeihs** [perun-network/perun-eth-demo#19]
### Problem:
The following error occurs when running the demo walkthrough twice without restarting ganache-cli:
> WARN[0007] error while funding channel: fund asset: sending funding tx: depositing asset 0: VM Exception while processing transaction: revert wrong amount of ETH for deposit  channel=68c440c697c7b65ab8b43da7f0a11e44362198818846f2a92b6cc66ed0bf021d id=0xA298Fc05bccff341f340a11FffA30567a00e651f
ERRO[0007] accepting channel proposal: error while funding channel: fund asset: sending funding tx: depositing asset 0: VM Exception while processing transaction: revert wrong amount of ETH for deposit

### Steps to reproduce:

1. Start ganache-cli
2. Start Alice and Bob nodes
3. Open channel and send ether from Alice to Bob
4. Close channel and shutdown Alice and Bob
5. Start Alice and Bob again (don't restart ganache-cli)
6. Open channel and send ether from Alice to Bob

**Comment by ggwpez** [comment]
*Alice* will deploy the contracts twice. You can try it by setting the the contract addresses in `alice.yaml` before the second run.

**Comment by matthiasgeihs** [comment]
i see. can you explain what goes wrong there? what happens when Alice tries to overwrite the contract? should we present an error if she tries that but the contract is already there?

**Comment by ggwpez** [comment]
> i see. can you explain what goes wrong there? what happens when Alice tries to overwrite the contract? should we present an error if she tries that but the contract is already there?

On the second start *Alice* deploys the contracts again to an address unknown to *Bob*.  
*Alice* then funds the new contracts and *Bob* the old ones, this obviously does not work for at least one reason.  
The best way would be to have a `DeployAdjudicatorTo(Address)` and `DeployAssetHolderETHTo(Address)` which is idempotent if the contracts are already present.  
Since *go-perun* does not export this functionality (yet), we could maybe change the behaviour of the the config to something like `adjudicator: 0xDc4A7e107aD6dBDA1870df34d70B51796BBd1335|deploy` fro *Alice*, whereas *Alice* deploys the contracts iff they are not found at the given Address. This would then only work for a fresh ganach, since *Alice* can not tell *Bob* the new contract addresses right now.

**Comment by ggwpez** [comment]
What we could also do, is to create a specific *deploy* command, which can be called by the user. What do you think? Any other ideas?

**Comment by matthiasgeihs** [comment]
ah, i get it. i thought contract address only depends on the address of the contract creator and the bytecode, but [source](https://ethereum.stackexchange.com/questions/760/how-is-the-address-of-an-ethereum-contract-computed#:~:text=The%20address%20for%20an%20Ethereum,then%20hashed%20with%20Keccak%2D256.) says it also depends on the nonce. This is why it changes.

I like the idea of supporting `adjudicator: 0xDc4A7e107aD6dBDA1870df34d70B51796BBd1335|deploy`. I will give it a try. I also like the idea of giving the user commands to deploy and to load contracts from addresses. This will probably require more source code modifications than the first approach.
